services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
  db:
    image: mariadb:10.11
    volumes:
      - dev-db-data:/var/lib/mariadb/data
    environment:
      - MARIADB_ROOT_PASSWORD=some_root_password
      - MARIADB_DATABASE=devdb
      - MARIADB_USER=devuser
      - MARIADB_PASSWORD=changeme
    ports:
      - "3306:3306"
    depends_on:
      - redis
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-psome_root_password" ]
      interval: 5s
      timeout: 5s
      retries: 10


volumes: #외부 저장소 정의
  dev-db-data: